books/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from books.views import *

urlpatterns = patterns('',
    url(r'^$', index),
)

urlpatterns += patterns('',
    # existing patterns here...
    (r'^login/$', login, {'template_name':'books/login.html'}),
)

urlpatterns += patterns('',
    url(r'^author/$', AuthorList.as_view(), name='author-list'),
    url(r'^author/page(?P<page>[0-9]+)/$', AuthorList.as_view(), name='author-list'),
    url(r'^author/(?P<pk>\d+)/$', AuthorDetail.as_view(), name='author-detail'),
    url(r'^author/new/$', AuthorCreate.as_view(), name='author-new'),
    url(r'^author/(?P<pk>\d+)/update/$', AuthorUpdate.as_view(), name='author-update'),
    url(r'^author/(?P<pk>\d+)/delete/$', AuthorDelete.as_view(), name='author-delete'),
)

urlpatterns += patterns('',
    url(r'^publisher/$', PublisherList.as_view(), name='publisher-list'),
    url(r'^publisher/page(?P<page>[0-9]+)/$', PublisherList.as_view(), name='publisher-list'),
    url(r'^publisher/(?P<pk>\d+)/$', PublisherDetail.as_view(), name='publisher-detail'),
    url(r'^publisher/new/$', PublisherCreate.as_view(), name='publisher-new'),
    url(r'^publisher/(?P<pk>\d+)/update/$', PublisherUpdate.as_view(), name='publisher-update'),
    url(r'^publisher/(?P<pk>\d+)/delete/$', PublisherDelete.as_view(), name='publisher-delete'),
)

urlpatterns += patterns('',
    url(r'^book/$', BookList.as_view(), name='book-list'),
    url(r'^book/page(?P<page>[0-9]+)/$', BookList.as_view(), name='book-list'),
    url(r'^book/(?P<pk>\d+)/$', BookDetail.as_view(), name='book-detail'),
    url(r'^book/new/$', BookCreate.as_view(), name='book-new'),
    url(r'^book/(?P<pk>\d+)/update/$', BookUpdate.as_view(), name='book-update'),
    url(r'^book/(?P<pk>\d+)/delete/$', BookDelete.as_view(), name='book-delete'),
)

mysite2/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    (r'^admin/', include(admin.site.urls)),
    (r'^books/', include('books.urls', namespace="books")),
    (r'^login/$', login, {'template_name':'registration/login.html'}),
    (r'^logout/$', logout, {'template_name':'registration/logout.html'}),
)

urlpatterns += patterns('',
    # existing patterns here...
    (r'^search/$', 'search.views.search'),
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': 'C:/python_study/tinymce_4.0.20/tinymce/js/tinymce/' }),
    #(r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': 'C:/python_study/tinymce_3.5.10/tinymce/jscripts/tiny_mce/' }),
    (r'', include('django.contrib.flatpages.urls')),
)

books/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, null=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('books:author-detail', args=[self.id])

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:publisher-detail', args=[self.id])

    class Meta:
        ordering = ['name']

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:book-detail', args=[self.id])

books/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.
from books.models import Author, Publisher, Book

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from django.http import HttpResponse

# Index
def index(request):
	return render(request, 'books/index.html')

# Author
class AuthorList(ListView):
    model=Author
    paginate_by = 10
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(AuthorList, self).dispatch(request, *args, **kwargs)

class AuthorDetail(DetailView):
    model=Author

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(AuthorDetail, self).dispatch(request, *args, **kwargs)

class AuthorCreate(CreateView):
    model = Author
    template_name = 'books/object_create_form.html'
    success_url = reverse_lazy('books:author-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.add_author', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(AuthorCreate, self).dispatch(request, *args, **kwargs)

class AuthorUpdate(UpdateView):
    model = Author
    template_name = 'books/object_update_form.html'
    success_url = reverse_lazy('books:author-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.change_author', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(AuthorUpdate, self).dispatch(request, *args, **kwargs)

class AuthorDelete(DeleteView):
    model = Author
    template_name='books/object_confirm_delete.html'
    success_url = reverse_lazy('books:author-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.delete_author', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(AuthorDelete, self).dispatch(request, *args, **kwargs)

# Publisher
class PublisherList(ListView):
    model=Publisher
    paginate_by = 10

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(PublisherList, self).dispatch(request, *args, **kwargs)

class PublisherDetail(DetailView):
    model=Publisher

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(PublisherDetail, self).dispatch(request, *args, **kwargs)

class PublisherCreate(CreateView):
    model = Publisher
    template_name = 'books/object_create_form.html'
    success_url = reverse_lazy('books:publisher-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.add_publisher', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(PublisherCreate, self).dispatch(request, *args, **kwargs)

class PublisherUpdate(UpdateView):
    model = Publisher
    template_name = 'books/object_update_form.html'
    success_url = reverse_lazy('books:publisher-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.change_publisher', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(PublisherUpdate, self).dispatch(request, *args, **kwargs)

class PublisherDelete(DeleteView):
    model = Publisher
    template_name='books/object_confirm_delete.html'
    success_url = reverse_lazy('books:publisher-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.delete_publisher', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(PublisherDelete, self).dispatch(request, *args, **kwargs)

# Book
class BookList(ListView):
    model=Book
    paginate_by = 10

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(BookList, self).dispatch(request, *args, **kwargs)

class BookDetail(DetailView):
    model=Book

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):        
        return super(BookDetail, self).dispatch(request, *args, **kwargs)

class BookCreate(CreateView):
    model = Book
    fields = ('title', 'publisher', 'publication_date', 'authors')
    #template_name = 'books/object_create_form.html'
    template_name = 'books/book_create_form.html'
    success_url = reverse_lazy('books:book-list')

    @method_decorator(login_required)
    @method_decorator(permission_required('books.add_book', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(BookCreate, self).dispatch(request, *args, **kwargs)

class BookUpdate(UpdateView):
    model = Book
    fields = ('title', 'publisher', 'publication_date', 'authors')
    #template_name = 'books/object_update_form.html'
    template_name = 'books/book_update_form.html'
    success_url = reverse_lazy('books:book-list')

    @method_decorator(login_required)
    @method_decorator(permission_required('books.change_book', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(BookUpdate, self).dispatch(request, *args, **kwargs)

class BookDelete(DeleteView):
    model = Book
    template_name='books/object_confirm_delete.html'
    success_url = reverse_lazy('books:book-list',)

    @method_decorator(login_required)
    @method_decorator(permission_required('books.delete_book', login_url='/books/login/'))
    def dispatch(self, request, *args, **kwargs):        
        return super(BookDelete, self).dispatch(request, *args, **kwargs)

templates/books/author_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Author Detail' %}{% endblock %}

{% block content %}
<div>
	<a href='../..'>{% trans 'Books Index' %}</a>&rsaquo;<a href='..'>{% trans 'Author List' %}</a>&rsaquo;{% trans 'Author Detail' %}
</div>
<h2>{% trans 'Author Detail' %}</h2>
<table  border=1 bordercolor="black">
	<tr bgcolor="#80ffff"  align=center>
		<td width=100>{% trans 'Item Name' %}</td><td width=200>{% trans 'Item Value' %}</td>
	</tr>
	<tr><td>{% trans 'First Name' %}</td><td>{{ object.first_name }}</td><tr>
	<tr><td>{% trans 'Last Name' %}</td><td>{{ object.last_name }}</td><tr>
	<tr><td>{% trans 'E-Mail' %}</td><td>{{ object.email }}</td><tr>
</table>
<br/>

<pre><a href="{% url 'books:author-delete' pk=object.id %}">{% trans 'Delete' %}</a>  <a href="{% url 'books:author-update' pk=object.id %}">{% trans 'Update' %}</a></pre>
{% endblock %}

templates/books/author_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div>
		<a href='..'>{% trans 'Books Index' %}</a>&rsaquo;{% trans 'Author List' %}
	</div>
	<h2>{% trans 'Author List' %}</h2>
	{% if object_list %}
		<ul>
			{% for object in object_list %}
				<li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
			{% endfor %}
		</ul>
		{%if is_paginated %}
			<hr>
			<div class="pagination">
				<span class="page-links">
					{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}">previous</a>
					{% endif %}
					<span class="page-current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>
			<hr>
		{% endif %}
	{% else %}
		<p>{% trans 'None of authors was founded.' %}</p>
	{% endif %}
	
	<a href="{% url 'books:author-new' %}">{% trans 'Create' %}</a>
{% endblock %}

templates/books/book_create_form.html
{% extends "base4book.html" %}
{% load i18n %}

{% block title %}{% trans 'Create' %}{% endblock %}

{% block content %}
<div>
	<a href='../..'>{% trans 'Books Index' %}</a>&rsaquo;<a href='..'>{% trans 'Book List' %}</a>&rsaquo;{% trans 'Create' %}
</div>
<h2>{% trans 'Create' %}</h2>
	<form action="" method="post" class="form-horizontal">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<script type="text/javascript">
				addEvent(window, "load", function(e) { SelectFilter.init("id_authors", "authors", 0, "{{ STATIC_URL }}admin/"); });
			</script>
		</table>
		<div class="submit-row">
			<input type="submit" value="{% trans 'Create' %}" />
		</div>
	</form>
{% endblock %}
</body>

templates/books/book_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Book Detail' %}{% endblock %}

{% block content %}
<div>
	<a href='../..'>{% trans 'Books Index' %}</a>&rsaquo;<a href='..'>{% trans 'Book List' %}</a>&rsaquo;{% trans 'Book Detail' %}
</div>
<h2>{% trans 'Book Detail' %}</h2>
<table  border=1 bordercolor="black">
	<tr bgcolor="#80ffff"  align=center>
		<td width=120>{% trans 'Item Name' %}</td><td width=300>{% trans 'Item Value' %}</td>
	</tr>
	<tr><td>{% trans 'Title' %}</td><td>{{ object.title }}</td><tr>
	<tr><td>{% trans 'Authors' %}</td>
		<td>
			{% if object.authors %}
				{% for author in object.authors.all %}
					{{ author }} <br />
				{% endfor %}
			{% else %}
				{% trans 'None of books was founded.' %}
			{% endif %}
		</td>
	<tr>
	<tr><td>{% trans 'Publisher' %}</td><td>{{ object.publisher }}</td><tr>
	<tr><td>{% trans 'Publication Date' %}</td><td>{{ object.publication_date }}</td><tr>
</table>
<br/>

<pre><a href="{% url 'books:book-delete' pk=object.id %}">{% trans 'Delete' %}</a>  <a href="{% url 'books:book-update' pk=object.id %}">{% trans 'Update' %}</a></pre>
{% endblock %}

templates/books/book_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div>
		<a href='..'>{% trans 'Books Index' %}</a>&rsaquo;{% trans 'Book List' %}
	</div>
	<h2>{% trans 'Book List' %}</h2>
	{% if object_list %}
		<ul>
			{% for object in object_list %}
				<li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
			{% endfor %}
		</ul>
		{%if is_paginated %}
			<hr>
			<div class="pagination">
				<span class="page-links">
					{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}">previous</a>
					{% endif %}
					<span class="page-current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>
			<hr>
		{% endif %}
	{% else %}
		<p>{% trans 'None of books was founded.' %}(</p>
	{% endif %}
	
	<a href="{% url 'books:book-new' %}">{% trans 'Create' %}</a>
{% endblock %}

templates/books/book_update_form.html
{% extends "base4book.html" %}
{% load i18n %}

{% block title %}{% trans 'Update' %}{% endblock %}

{% block content %}
<div>
	<a href='../..'>{% trans 'Books Index' %}</a>&rsaquo;<a href='..'>{% trans 'Book Detail' %}</a>&rsaquo;{% trans 'Update' %}
</div>
<h2>{% trans 'Update' %}</h2>
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<div class="form-row">
		{{ form.as_p }}
		<script type="text/javascript">
			addEvent(window, "load", function(e) { SelectFilter.init("id_authors", "authors", 0, "{{ STATIC_URL }}admin/"); });
		</script>
	</div>
	<div class="submit-row">
		<input type="submit" value="{% trans 'Update' %}" />
	</div>
</form>
{% endblock %}

templates/books/books4author.html
{% comment %}
Chapter 9 page 15 / 17 template inclusion tag
{% endcomment %}
{% load books/books_extras %}

{% books_for_author author %}

templates/books/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Books Index' %}{% endblock %}

{% block content %}
<h2>{% trans 'Books Index' %}</h2>
<form action="" method="post">
	{% csrf_token %}
	<ul>
		<li><a href="{% url 'books:author-list' %}">{% trans 'Author List' %}</a></li>
		<li><a href="{% url 'books:publisher-list' %}">{% trans 'Publisher List' %}</a></li>
		<li><a href="{% url 'books:book-list' %}">{% trans 'Book List' %}</a></li>
	</ul>
</form>
{% endblock %}

templates/books/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Log in' %}{% endblock %}

{% block content %}
	<h2>{% trans 'Sorry, that is not a sufficient authorization.' %}</h2>

	<form action="" method="post">
		{% csrf_token %}
		<table>
		<tr>
			<td>{% trans 'User' %}</td>
			<td>{{ form.username }}</td>
		</tr>
		<tr>
			<td>{% trans 'Password' %}</td>
			<td>{{ form.password }}</td>
		</tr>
		</table>
		
		<input type="submit" value="{% trans 'Log in' %}" />
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
{% endblock %}

templates/books/object_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Confirm' %}{% endblock %}

{% block content %}
<div>
	<a href='..'>{% trans 'Back' %}</a>
</div>
<h2>{% trans 'Delete Confirm' %}</h2>
<form action="" method="post">{% csrf_token %}
    <p>{% trans 'Are you sure that you want to delete' %} "{{ object }}" ?</p>
    <input type="submit" value="{% trans 'Confirm' %}" />
</form>
{% endblock %}

templates/books/object_create_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Create' %}{% endblock %}

{% block content %}
<div>
	<a href='..'>{% trans 'Back' %}</a>
</div>
<h2>{% trans 'Create' %}</h2>
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="{% trans 'Create' %}" />
</form>
{% endblock %}

templates/books/object_update_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Update' %}{% endblock %}

{% block content %}
<div>
	<a href='..'>{% trans 'Back' %}</a>
</div>
<h2>{% trans 'Update' %}</h2>
<div class="form-row">
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<br />
		<input type="submit" value="{% trans 'Update' %}" />
	</form>
</div>
{% endblock %}

templates/books/publisher_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Publisher Detail' %}{% endblock %}

{% block content %}
<div>
	<a href='../..'>{% trans 'Books Index' %}</a>&rsaquo;<a href='..'>{% trans 'Publisher List' %}</a>&rsaquo;{% trans 'Publisher Detail' %}
</div>
<h2>{% trans 'Publisher Detail' %}</h2>
<table  border=1 bordercolor="black">
	<tr bgcolor="#80ffff"  align=center>
		<td width=120>{% trans 'Item Name' %}</td><td width=200>{% trans 'Item Value' %}</td>
	</tr>
	<tr><td>{% trans 'Name' %}</td><td>{{ object.name }}</td><tr>
	<tr><td>{% trans 'Address' %}</td><td>{{ object.address }}</td><tr>
	<tr><td>{% trans 'State Province' %}</td><td>{{ object.state_province }}</td><tr>
	<tr><td>{% trans 'City' %}</td><td>{{ object.city }}</td><tr>
	<tr><td>{% trans 'Country' %}</td><td>{{ object.country }}</td><tr>
	<tr><td>{% trans 'Website' %}</td><td>{{ object.website }}</td><tr>
</table>
<br/>

<pre><a href="{% url 'books:publisher-delete' pk=object.id %}">{% trans 'Delete' %}</a>  <a href="{% url 'books:publisher-update' pk=object.id %}">{% trans 'Update' %}</a></pre>
{% endblock %}

templates/books/publisher_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div>
		<a href='..'>{% trans 'Books Index' %}</a>&rsaquo;{% trans 'Publisher List' %}
	</div>
	<h2>{% trans 'Publisher List' %}</h2>
	{% if object_list %}
		<ul>
			{% for object in object_list %}
				<li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
			{% endfor %}
		</ul>
		{%if is_paginated %}
			<hr>
			<div class="pagination">
				<span class="page-links">
					{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}">previous</a>
					{% endif %}
					<span class="page-current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>
			<hr>
		{% endif %}
	{% else %}
		<p>{% trans 'None of publishers was founded.' %}(</p>
	{% endif %}
	
	<a href="{% url 'books:publisher-new' %}">{% trans 'Create' %}</a>
{% endblock %}